version: "3.8"
services:

  dep_search:
    container_name: dep_search
    build: 
        context: .
        dockerfile: Dockerfile_api_gui
    ports:
      - "5000:5000"
    networks:
      - net
    volumes:
      - ./logs/:/api_gui/logs/

  nginx:
      build: 
        context: .
        dockerfile: DockerfileNginx
      restart: always
      ports:
        - "80:80"
      depends_on:
        - dep_search
        #- dep_search_old
      networks:
        - net

      

networks:
  net:

